<div class="row">
	<div id= "form" class="col-xs-6 col-sm-1">
		<?php 
		$form = $this->form;
		$form->prepare();
		//abrir formulario
		echo $this->form()->openTag($form);
		//linea para obtener el campo
		echo $this->formElement($form->get('id'));

		echo $this->formlabel($form->get('nombre'));
		//linea para obtener el texto del campo
		echo $this->formElement($form->get('nombre'));

		echo $this->formlabel($form->get('precio'));
		echo $this->formElement($form->get('precio'));

	
		echo $this->formElement($form->get('submit'));
		//cerrar formulario
		echo $this->form()->closeTag();
		?>
	</div>
</div>